import { spawn as childSpawn, type ChildProcess } from "node:child_process";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync } from "node:fs";
import { randomUUID } from "node:crypto";
import { createServer } from "node:net";
import { tmpdir } from "node:os";
import { dirname, isAbsolute, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { PulsarClient, PulsarRuntimeError, type PulsarPrismLogEvent } from "@clodocapeo/pulsar-client";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

/** Default location of the bundled binaries inside this package. */
const DEFAULT_BINARIES = resolve(__dirname, "..", "binaries");

export interface SpawnOptions {
  /** Override the directory containing bin/64bit/pulsar.exe.
   *  Default: <package>/binaries (populated by postinstall). */
  binariesPath?: string;

  /** Extra env vars for pulsar.exe. Common ones:
   *    PULSAR_RUNTIME_INSTANCE_ID  validated identity (auto-generated by spawn)
   *    PULSAR_RUNTIME_DIR          explicit per-instance working directory
   *    PULSAR_LEGACY_ALIAS         required | dedicated | off (default opportunistic)
   *    PULSAR_CAPTURE_WINDOW   "<title>:<class>:<exe>" for window_capture
   *    PULSAR_FPS              30 / 60 / etc.
   *    PULSAR_VIDEO_BITRATE    kbps
   *    PULSAR_AUDIO_BITRATE    kbps
   *    PULSAR_RECORD_DIR       output dir for the singleton recorder
   *    PULSAR_PROCESS_AUDIO_NAME  exe name for per-process audio
   *    PULSAR_ADAPTIVE_BITRATE off  to disable the worker
   */
  env?: Record<string, string>;

  /** How long to wait for "ready, idling" on stdout. Default 30 s. */
  readyTimeoutMs?: number;

  /** Optional log forwarder. Receives one stdout/stderr line at a time. */
  onLog?: (stream: "stdout" | "stderr", line: string) => void;

  /** Optional structured projection of runtime lifecycle/native log lines. */
  onPrismLog?: (event: PulsarPrismLogEvent) => void;

  /** Test-only escape hatch: spawn a different executable instead of
   *  the bundled pulsar.exe. The launched process must still print the
   *  ready marker on stdout and create obs-websocket/config.json under
   *  the cwd. Used by the package's own vitest suite -- not a public
   *  API for normal callers.
   *  @internal */
  launchCommand?: { exe: string; args?: string[] };
}

export interface SpawnedPulsar {
  /** Connected PulsarClient ready for vendor calls. */
  client: PulsarClient;

  /** Underlying child process. Most callers should use shutdown() instead
   *  of touching this directly, but it's exposed for advanced use cases
   *  (sending custom signals, reading stdio, etc.). */
  child: ChildProcess;

  /** WebSocket port the obs-websocket server is bound to. */
  port: number;

  /** libobs version string parsed from the boot log
   *  (e.g. "32.1.2-1-g8c23ba721-pulsar"). */
  libobsVersion: string;

  /** Validated identity of this isolated Pulsar process. */
  runtimeInstanceId: string;

  /** Process-local cwd/config/log/recording namespace. */
  runtimeDir: string;

  /** Disconnect the WS client and terminate pulsar.exe. Resolves once
   *  the process has exited. Idempotent. */
  shutdown(): Promise<void>;
}

interface ObsWebSocketConfig {
  server_password?: string;
  server_port?: number;
}

const READY_MARKER = "pulsar-headless: libobs ";
const IDLE_MARKER = "ready, idling";

/**
 * Spawn pulsar.exe and return a connected PulsarClient.
 *
 * The executable is resolved from the bundle, while each child process is
 * started in its own runtime directory.  The native bootstrap resolves OBS
 * plugins from the executable location and uses the runtime directory for
 * config, logs, recordings and namespaced DirectShow mappings.
 *
 * @example
 *   const pulsar = await spawn({
 *     env: { PULSAR_CAPTURE_WINDOW: "Untitled - Notepad:Notepad:notepad.exe" },
 *   });
 *   await pulsar.client.destinations.create({ kind: "twitch", key });
 *   await pulsar.shutdown();
 */
export async function spawn(opts: SpawnOptions = {}): Promise<SpawnedPulsar> {
  const emitRuntimeError = (code: string, message: string, details: Record<string, unknown> = {}): void => {
    opts.onPrismLog?.({
      schemaVersion: 1,
      severity: "error",
      domain: "service",
      source: "pulsar.runtime",
      code,
      message,
      context: { action: "spawn" },
      details,
    });
  };
  const binariesPath = opts.binariesPath ?? DEFAULT_BINARIES;
  const binaryCwd = join(binariesPath, "bin", "64bit");

  // #243: every child gets an explicit identity and a private cwd.  The
  // native bootstrap validates the same identifier and holds an instance
  // lock before touching config, logs, recordings or DirectShow mappings.
  const requestedRuntimeId = opts.env?.PULSAR_RUNTIME_INSTANCE_ID;
  const runtimeInstanceId = requestedRuntimeId || `node-${randomUUID().replace(/-/g, "")}`;
  if (!/^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$/.test(runtimeInstanceId)) {
    emitRuntimeError("PULSAR_RUNTIME_ID_INVALID", `Invalid PULSAR_RUNTIME_INSTANCE_ID '${runtimeInstanceId}'.`, {
      runtimeInstanceId,
    });
    throw new PulsarRuntimeError(
      "PULSAR_RUNTIME_ID_INVALID",
      "PULSAR_RUNTIME_INSTANCE_ID must match [A-Za-z0-9][A-Za-z0-9._-]{0,63}.",
      { action: "spawn", runtimeInstanceId },
    );
  }

  const requestedRuntimeDir = opts.env?.PULSAR_RUNTIME_DIR;
  const ownsRuntimeDir = requestedRuntimeDir === undefined || requestedRuntimeDir.length === 0;
  const requestedRuntimeRoot = opts.env?.PULSAR_RUNTIME_ROOT ?? process.env.PULSAR_RUNTIME_ROOT;
  const runtimeRoot = resolve(requestedRuntimeRoot || tmpdir());
  let runtimeDir: string;
  if (!ownsRuntimeDir) {
    runtimeDir = resolve(requestedRuntimeDir!);
    mkdirSync(runtimeDir, { recursive: true });
  } else {
    mkdirSync(runtimeRoot, { recursive: true });
    runtimeDir = mkdtempSync(join(runtimeRoot, `pulsar-${runtimeInstanceId}-`));
  }
  const configPath = join(runtimeDir, "obs-websocket", "config.json");

  const cleanupRuntimeDir = (): void => {
    if (!ownsRuntimeDir) return;
    const relativeRuntimeDir = relative(runtimeRoot, runtimeDir);
    if (isAbsolute(relativeRuntimeDir) || relativeRuntimeDir.startsWith("..") ||
        !relativeRuntimeDir.startsWith(`pulsar-${runtimeInstanceId}-`)) return;
    try {
      rmSync(runtimeDir, { recursive: true, force: true, maxRetries: 3, retryDelay: 50 });
    } catch {
      // Antivirus/CEF can briefly retain a child file. The path is uniquely
      // generated for this call and can be reaped by the caller later.
    }
  };

  const childEnv: NodeJS.ProcessEnv = {
    ...process.env,
    ...opts.env,
    PULSAR_RUNTIME_INSTANCE_ID: runtimeInstanceId,
    PULSAR_RUNTIME_DIR: runtimeDir,
  };
  // The child starts in runtimeDir, so an explicitly relative root would be
  // interpreted differently by native code. Publish the absolute root used
  // by this helper whenever it owns the generated namespace or a caller
  // supplied a root, keeping instance/alias leases on the same state tree.
  if (ownsRuntimeDir || requestedRuntimeRoot) childEnv.PULSAR_RUNTIME_ROOT = runtimeRoot;
  // An inherited PULSAR_PORT is not a safe default for a second child. Only
  // an explicit per-spawn value opts out of the free-port allocator.
  if (opts.env?.PULSAR_PORT === undefined || opts.env.PULSAR_PORT === "" || opts.env.PULSAR_PORT === "0") {
    try {
      childEnv.PULSAR_PORT = String(await pickFreePort());
    } catch (error) {
      cleanupRuntimeDir();
      throw error;
    }
  }

  // Resolve the executable. Default = bundled pulsar.exe; tests can pass
  // launchCommand to swap in a fake.
  let exe: string;
  let args: string[];
  if (opts.launchCommand) {
    exe = opts.launchCommand.exe;
    args = opts.launchCommand.args ?? [];
  } else {
    exe = join(binaryCwd, "pulsar.exe");
    args = [];
    if (!existsSync(exe)) {
      cleanupRuntimeDir();
      emitRuntimeError("PULSAR_BINARY_UNAVAILABLE", `pulsar.exe not found at ${exe}.`, { binaryPath: exe });
      throw new PulsarRuntimeError(
        "PULSAR_BINARY_UNAVAILABLE",
        `pulsar.exe not found at ${exe}. ` +
          `Run \`npm install\` to trigger the postinstall download, ` +
          `or set binariesPath to a local checkout.`,
        { action: "spawn", binaryPath: exe },
      );
    }
  }

  let child: ChildProcess;
  try {
    child = childSpawn(exe, args, {
      cwd: runtimeDir,
      env: childEnv,
      stdio: ["ignore", "pipe", "pipe"],
      windowsHide: true,
    });
  } catch (error) {
    cleanupRuntimeDir();
    throw error;
  }

  // Keep failure cleanup deterministic. In particular, a ready timeout must
  // terminate the child before releasing the generated cwd; otherwise a
  // failed boot can retain the instance lock and leave a partial namespace.
  const terminateChild = async (): Promise<void> => {
    if (child.exitCode !== null || child.signalCode !== null) return;
    child.kill();
    await new Promise<void>((resolveExit) => {
      if (child.exitCode !== null || child.signalCode !== null) {
        resolveExit();
        return;
      }
      const forceTimer = setTimeout(() => {
        if (child.exitCode === null && child.signalCode === null)
          child.kill("SIGKILL");
        resolveExit();
      }, 5_000);
      child.once("exit", () => {
        clearTimeout(forceTimer);
        resolveExit();
      });
    });
  };

  const readyTimeout = opts.readyTimeoutMs ?? 30_000;

  let libobsVersion = "";
  let resolveReady!: () => void;
  let rejectReady!: (err: Error) => void;
  const ready = new Promise<void>((res, rej) => {
    resolveReady = res;
    rejectReady = rej;
  });

  const watchdog = setTimeout(() => {
    emitRuntimeError("PULSAR_READY_TIMEOUT", `pulsar.exe did not signal ready within ${readyTimeout}ms`, {
      timeoutMs: readyTimeout,
    });
    rejectReady(new PulsarRuntimeError("PULSAR_READY_TIMEOUT", `pulsar.exe did not signal ready within ${readyTimeout}ms`, { action: "spawn", timeoutMs: readyTimeout }));
  }, readyTimeout);

  const handleLine = (stream: "stdout" | "stderr", line: string) => {
    if (line.length === 0) return;
    if (opts.onLog) opts.onLog(stream, line);
    opts.onPrismLog?.({
      schemaVersion: 1,
      severity: /error|fail|fatal|refus|declin|unavail/i.test(line) ? "error" : /warn|skip|partial/i.test(line) ? "warning" : "info",
      domain: "service",
      source: "pulsar.process",
      code: "PULSAR_PROCESS_LOG",
      message: redactNativeLine(line),
      context: { stream },
      details: {},
    });
    // pulsar-headless prints exactly:
    //   "pulsar-headless: libobs <version> ready, idling (Ctrl+C to exit)"
    // when boot is complete.
    if (stream === "stdout" && line.includes(IDLE_MARKER) && line.includes(READY_MARKER)) {
      const slice = line.slice(line.indexOf(READY_MARKER) + READY_MARKER.length);
      libobsVersion = slice.split(" ", 1)[0] ?? "";
      clearTimeout(watchdog);
      resolveReady();
    }
  };

  attachLineReader(child, "stdout", (l) => handleLine("stdout", l));
  attachLineReader(child, "stderr", (l) => handleLine("stderr", l));

  child.on("exit", (code, signal) => {
    clearTimeout(watchdog);
    emitRuntimeError("PULSAR_PROCESS_EXITED", `pulsar.exe exited prematurely (code=${code}, signal=${signal})`, {
      exitCode: code,
      signal,
    });
    rejectReady(new PulsarRuntimeError("PULSAR_PROCESS_EXITED", `pulsar.exe exited prematurely (code=${code}, signal=${signal})`, { action: "spawn", exitCode: code, signal }));
    cleanupRuntimeDir();
  });

  child.on("error", (error) => {
    clearTimeout(watchdog);
    emitRuntimeError("PULSAR_PROCESS_ERROR", `pulsar.exe process error: ${error.message}`, {
      message: error.message,
    });
    rejectReady(new PulsarRuntimeError("PULSAR_PROCESS_ERROR", `pulsar.exe process error: ${error.message}`, {
      action: "spawn",
    }));
    cleanupRuntimeDir();
  });

  try {
    await ready;
  } catch (error) {
    await terminateChild();
    cleanupRuntimeDir();
    throw error;
  }

  // obs-websocket writes its config.json on first run -- after the
  // ready marker, the file is guaranteed to exist with port + password.
  if (!existsSync(configPath)) {
    await terminateChild();
    cleanupRuntimeDir();
    emitRuntimeError("PULSAR_CONFIG_MISSING", `obs-websocket config not found at ${configPath} (boot incomplete?)`, {
      configPath,
    });
    throw new PulsarRuntimeError("PULSAR_CONFIG_MISSING", `obs-websocket config not found at ${configPath} (boot incomplete?)`, { action: "spawn" });
  }
  let config: ObsWebSocketConfig;
  try {
    config = JSON.parse(readFileSync(configPath, "utf8")) as ObsWebSocketConfig;
  } catch (error) {
    await terminateChild();
    cleanupRuntimeDir();
    const message = `could not parse obs-websocket config at ${configPath}`;
    emitRuntimeError("PULSAR_CONFIG_INVALID", message, { configPath });
    throw new PulsarRuntimeError("PULSAR_CONFIG_INVALID", message, { action: "spawn" });
  }
  const port = config.server_port ?? 4455;
  if (!Number.isInteger(port) || port < 1 || port > 65_535) {
    await terminateChild();
    cleanupRuntimeDir();
    const message = `obs-websocket config contains invalid server_port at ${configPath}`;
    emitRuntimeError("PULSAR_CONFIG_INVALID", message, { configPath });
    throw new PulsarRuntimeError("PULSAR_CONFIG_INVALID", message, { action: "spawn" });
  }
  const password = config.server_password;

  const client = new PulsarClient();
  client.on("prismLog", (event) => opts.onPrismLog?.(event));
  try {
    await client.connect({
      url: `ws://127.0.0.1:${port}`,
      ...(password !== undefined ? { password } : {}),
    });
  } catch (error) {
    await terminateChild();
    cleanupRuntimeDir();
    throw error;
  }

  let shutdownPromise: Promise<void> | null = null;
  const shutdown = async (): Promise<void> => {
    if (shutdownPromise) return shutdownPromise;
    shutdownPromise = (async () => {
      try {
        await client.disconnect();
      } catch {
        // Already closed -- swallow.
      }
      await terminateChild();
      cleanupRuntimeDir();
    })();
    return shutdownPromise;
  };

  return { client, child, port, libobsVersion, runtimeInstanceId, runtimeDir, shutdown };
}

function pickFreePort(): Promise<number> {
  return new Promise((resolvePort, rejectPort) => {
    const server = createServer();
    server.once("error", rejectPort);
    server.listen(0, "127.0.0.1", () => {
      const address = server.address();
      const port = typeof address === "object" && address !== null ? address.port : 0;
      server.close((error) => {
        if (error) rejectPort(error);
        else if (port > 0) resolvePort(port);
        else rejectPort(new Error("OS returned no loopback port"));
      });
    });
  });
}

/** Reads `child[stream]` line-by-line and dispatches each completed line. */
function attachLineReader(
  child: ChildProcess,
  stream: "stdout" | "stderr",
  onLine: (line: string) => void,
): void {
  const out = child[stream];
  if (!out) return;
  let buf = "";
  out.setEncoding("utf8");
  out.on("data", (chunk: string) => {
    buf += chunk;
    let idx;
    while ((idx = buf.indexOf("\n")) >= 0) {
      const line = buf.slice(0, idx).replace(/\r$/, "");
      buf = buf.slice(idx + 1);
      onLine(line);
    }
  });
  out.on("end", () => {
    if (buf.length > 0) onLine(buf.replace(/\r$/, ""));
  });
}

function redactNativeLine(line: string): string {
  return line
    .replace(/(password|token|secret|stream[-_ ]?key)\s*[:=]\s*[^\s,;]+/gi, "$1=[redacted]")
    .slice(0, 512);
}
